spring:
  application:
    name: gamesj
  datasource:
    url: ${DB_URL:jdbc:mysql://barryonweb.com:3306/db_games}
    username: ${DB_USER:barry75}
    password: ${DB_PASSWORD:abc123}
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  graphql:
    path: /graphql
server:
  port: 8082
websocket:
  timeout-mins: 10
  check-interval-sec: 45
useridle:
  timeout-mins: 10
  check-interval-sec: 35
invitation:
  timeout-sec: 15

