spring:
  application:
    name: gamesj
  datasource:
    url: jdbc:mysql://barryonweb.com:3306/db_games?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: barry75
    password: abc123
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
websocket:
  timeout-mins: 1
  check-interval-sec: 45
useridle:
  timeout-mins: 2
  check-interval-sec: 35
invitation:
  timeout-sec: 15

