spring:
  application:
    name: gamesj
  datasource:
    url: jdbc:mysql://localhost:3306/db_games?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: barry75
    password: abc123
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
websocket:
  idle-timeout-minutes: 3
  check-interval-ms: 300000
useridle:
  timeout-mins: 2
  check-interval-sec: 60

