name: Deploy Java Backend

env:
  SSH_PORT: 2026

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Setup Java and Maven
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # Build backend
      - name: Build backend
        run: |
          mvn clean package -DskipTests

      # Setup SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Add server to known_hosts
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $SSH_PORT barryonweb.com >> ~/.ssh/known_hosts

      # Copy published files to server
      - name: Deploy backend files 
        run: |
          ssh -p $SSH_PORT barry75@barryonweb.com "mkdir -p /var/www/games/gamesj"
          scp -P $SSH_PORT target/gamesj-0.0.1-SNAPSHOT.jar barry75@barryonweb.com:/var/www/games/gamesj/
      
      # Copy DB scripts to server
      - name: Copy DB scripts 
        run: |
          ssh -p $SSH_PORT barry75@barryonweb.com "mkdir -p /var/www/games/gamesj/data/mysql"
          scp -P $SSH_PORT -r src/main/resources/*.sql barry75@barryonweb.com:/var/www/games/gamesj/data/mysql/

      # Copy images to server
      - name: Deploy images 
        run: |
          ssh -p $SSH_PORT barry75@barryonweb.com "mkdir -p /var/www/games/gamesj/images"
          scp -P $SSH_PORT src/main/resources/static/images/*.png barry75@barryonweb.com:/var/www/games/gamesj/images/    

      # Deploy Nginx config and reload
      - name: Update Nginx config
        run: |
          ssh -p $SSH_PORT barry75@barryonweb.com "mkdir -p /var/www/games/nginx"
          scp -P $SSH_PORT gamesj barry75@barryonweb.com:/var/www/games/nginx/
          ssh -p $SSH_PORT barry75@barryonweb.com "
            sudo cp /var/www/games/nginx/gamesj /etc/nginx/sites-available/ &&
            sudo ln -sf /etc/nginx/sites-available/gamesj /etc/nginx/sites-enabled/ &&
            sudo nginx -t &&
            sudo systemctl reload nginx"

      # Copy service script and Restart backend via systemd
      - name: Copy backend service file and Restart backend service
        run: |
          scp -P $SSH_PORT gamesj.service barry75@barryonweb.com:/etc/systemd/system/
          ssh -p $SSH_PORT barry75@barryonweb.com "sudo systemctl restart gamesj"

      # See logs after restart
      - name: Show backend logs
        run: |
          ssh -p $SSH_PORT barry75@barryonweb.com "journalctl -u gamesj -n 50 --no-pager"

      # Dockerized test environment
      - name: Copy nginx config and Docker run script
        run: |
          scp -P $SSH_PORT gamesj-test barry75@barryonweb.com:/var/www/games/nginx/
          scp -P $SSH_PORT runtestDocker.sh barry75@barryonweb.com:/var/www/games/testenv/



 